//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
        }
    
        public int ID_HoaDon { get; set; }
        public int ID_ThanhToan { get; set; }
        public int ID_KM { get; set; }
        public int ID_TK { get; set; }
        public string DiaChiGiaoHang { get; set; }
        public int TrangThaiThanhToan { get; set; }
    
        public virtual CachThucThanhToan CachThucThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
