//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int ID_NV { get; set; }
        public string Ten { get; set; }
        public string SDT { get; set; }
    }
}
