//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinTK
    {
        public int ID_TT { get; set; }
        public string Ten { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public int ID_TK { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
